### ISSUE TITLE
white page on web

### ISSUE THREAD

**Issue by JamesDAdams** [avionmission/OpenShop#2]
Hi,

if a launch the npm run web i have a white page

Thanks.

**Comment by avionmission** [comment]
Hi,

Thank you for reaching out and your interest in this project.

I understand that you're experiencing an issue when running `npm run web`, and I appreciate your feedback. However, please note that our project is currently designed and optimized for mobile app development, and running it in a web environment is not a supported feature at this time.

If you're interested in using the template for web development, you may need to make some modifications to adapt it for web usage. Alternatively, you can explore other web-focused React projects that might better suit your needs.

If you encounter any issues or have questions related to mobile app development using our template, please feel free to ask, and we'll be happy to assist you.

Thank you for your understanding.

Best regards,
Avinash

**Comment by avionmission** [comment]
Hi,

Thank you for reaching out and your interest in this project.

I understand that you're experiencing an issue when running npm run web, and I appreciate your feedback. However, please note that our project is currently designed and optimized for mobile app development, and running it in a web environment is not a supported feature at this time.

If you're interested in using the template for web development, you may need to make some modifications to adapt it for web usage. Alternatively, you can explore other web-focused React projects that might better suit your needs.

If you encounter any issues or have questions related to mobile app development using our template, please feel free to ask, and we'll be happy to assist you.

Thank you for your understanding.

Best regards,
Avinash
